# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67211bb3506276f648e6d27f4e04d52e9844fa7f675b40c5b85ad744e6ae261b682a7c28537a73711ee7c7c4e34bf63d991665b6953c0dc6035723579aac0288

test:
  secret_key_base: b89f161d8caad42ec2079297e7885ef9bf2e28757a28615b7edd8cda82e3d1269e1d63d1319ca391f234f04e2d7ba2332cdb91749e81ea9237852f9e5378660f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
